# Generated by Django 5.1.7 on 2025-04-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototypes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.CharField(blank=True, choices=[('phd', 'PhD'), ('masters', 'Masters')], help_text='Only required if the user is a student.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Faculty/Staff'), ('student', 'Student'), ('general_user', 'General User')], max_length=15),
        ),
    ]
