# Generated by Django 5.1.7 on 2025-04-25 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototypes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prototype',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='prototype',
            name='supervisors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['staff', 'admin']}, related_name='supervising_prototypes', to=settings.AUTH_USER_MODEL),
        ),
    ]
